version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - fluen
networks:
  fluen:
    name: fluen
